apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-5d4b9d31e97949c8a7ff6424c144117b-depl
  labels:
    app: coll-5d4b9d31e97949c8a7ff6424c144117b
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-5d4b9d31e97949c8a7ff6424c144117b
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-5d4b9d31e97949c8a7ff6424c144117b
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-5d4b9d31e97949c8a7ff6424c144117b
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-5d4b9d31e97949c8a7ff6424c144117b
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping